name: Microsite

on:
  push:
    branches:
      - main
    paths:
      - "site/**"
      - "**/README.md"

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12
        with:
          skip_adding_nixpkgs_channel: true

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8
        with:
          name: fs2-site
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Building microsite 🚧"
        run: nix-shell --run "sbt '++2.13.3;microsite/publishMicrosite'"
