name: Cachix

on:
  push:
    branches:
      - main
    paths:
      - "nix/**"
      - "shell.nix"

jobs:
  update-nix-cache:
    env:
      CACHIX_SIGNING_KEY: "${{ secrets.CACHIX_SIGNING_KEY }}"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12
        with:
          skip_adding_nixpkgs_channel: true

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8
        with:
          name: fs2-site
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Update Nix cache"
        run: nix-store -qR --include-outputs $(nix-instantiate shell.nix) | cachix push fs2-site
